env: 'local'
port: ':8080'
server:
  address: 'localhost:8080'
  timeout: 4s
  idle_timeout: 30s



log-level: 'debug'

database_url: 'host=localhost port=5432 user=postgres password=admin dbname=postgres sslmode=disable'


